--- 
- hosts: all
  user: ansible
  become: yes
  connection: ssh


  tasks: 
    - name: install multiple packages
      yum: 
        name: ['git', 'which', 'docker', 'mysql', 'tree','wget','java','httpd']
        state: installed
