---
- hosts: all
  user: ansible
  connection: ssh
  become: yes

  tasks: 
    - name: creating multiple users
      user: name='{{item}}' state=present
      with_items:
            - Suresh
            - Krish
            - Srinu
            - Harish
            - omkar
            - Eshwar


