--- 
- hosts: all
  become: yes
  user: ansible
  connection: ssh


  tasks: 
    - name: remove pkg
      yum:
        name: httpd
        state: absent

    - name: stop service
      service: 
        name: httpd
        state: stopped
